import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, this might be handled more gracefully, but for this environment, an error is appropriate.
  throw new Error("API_KEY environment variable not set. Please ensure it is configured.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = async (file: File) => {
  const base64EncodedDataPromise = new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
        if (typeof reader.result === 'string') {
            resolve(reader.result.split(',')[1]);
        } else {
            reject(new Error("Failed to read file as Data URL"));
        }
    };
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file);
  });

  return {
    inlineData: { data: await base64EncodedDataPromise, mimeType: file.type },
  };
};

export const generatePassportPhoto = async (imageFile: File, backgroundColor: string): Promise<string> => {
  const imagePart = await fileToGenerativePart(imageFile);

  const textPart = {
    text: `Ultra-realistic passport photo of this person (exact face, 99% likeness, no changes). The person should be wearing a dark, professional 3-piece suit with a tie. They must have a neutral, closed-lip expression and be looking straight at the camera. Both ears and shoulders must be fully visible. The lighting must be even and balanced, without shadows on the face or background. The background should be a plain, uniform ${backgroundColor}. The final image should be cropped tightly around the head and shoulders, typical for a standard passport photo.`,
  };

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [imagePart, textPart],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  // Access the first candidate and its parts to find the image data.
  const candidate = response.candidates?.[0];
  if (!candidate || !candidate.content || !candidate.content.parts) {
      throw new Error("Invalid API response structure. No candidates found.");
  }

  for (const part of candidate.content.parts) {
    if (part.inlineData && part.inlineData.data) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API. The model may have refused the request.");
};